In [3]:
import numpy as np
import pandas as pd
from math import sqrt

In [6]:
#1.  How likely is it that you roll doubles when rolling two dice?
outcomes = [1,2,3,4,5,6]
sims = 10_000
trials = 2
rolls = np.random.choice(outcomes, size=(sims, trials))
rolls
sum_of_rolls = rolls.sum(axis=1)
(sum_of_rolls % 2
 


array([8, 6, 7, ..., 4, 3, 6])

In [82]:
#review
#represent outcomes
o = [1,2,3,4,5,6]
#create the data
n_simulations = 1_000_000
n_trials = 2
rolls = np.random.choice(o, size = (n_simulations,n_trials))
rolls



array([[3, 5],
       [2, 4],
       [6, 2],
       ...,
       [2, 6],
       [6, 2],
       [2, 5]])

In [81]:
#using a sum isnt the best option here, since we are looking for two matching elements,
#or the number of unique elements
np.unique(rolls[2])

array([2, 5])

In [84]:
lst_doubles = [len(np.unique(rolls[n])) for n in range(0, n_simulations - 1) if len(np.unique(rolls[n])) == 1]

# did not get to see next step calculated

In [77]:
#2.  If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# What is the probability of getting more than 3 heads?

outcomes = [1, 0] #one is heads, 0 is tails
flips = np.random.choice(outcomes, size=(10_000, 8), p=[0.50, 0.50])
flips
num_heads = flips.sum(axis=1)
(num_heads == 3).mean()
(num_heads > 3).mean()

0.6337

In [86]:
#review
n_sims = 1_000_000 #nrows
n_trials = 8 #ncolumns
heads = 1
tails = 0
flips = np.random.choice([heads, tails], size = (n_sims, n_trials))
flips

array([[0, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 1, 0],
       [0, 1, 1, ..., 1, 1, 1],
       ...,
       [0, 0, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 1, 1],
       [0, 1, 1, ..., 0, 1, 0]])

In [87]:
numheads = flips.sum(axis=1)
calculated_prob = (numheads == 3).mean()
calculated_prob

0.218241

In [88]:
calculated_prob = (numheads >= 3).mean()
calculated_prob

0.855153

In [13]:
#3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards 
# I drive past both have data science students on them?
outcomes = [1,1,1,0]
billboard = np.random.choice(outcomes, size=(10_000, 2))

ds_billboard = billboard.sum(axis=1)
(ds_billboard == 0).mean()

0.0614

In [92]:
#review
n_sims = 1_000_000
n_trials = 2
data_sci = 1
web_dev = 0
commutes = np.random.choice([data_sci, web_dev], size=(n_sims, n_trials), p = [0.25, 0.75])

In [94]:
calculated_prob = (commutes.sum(axis=1) ==2).mean()
calculated_prob

0.062817

In [35]:
#4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. 
#If on monday the machine is restocked with 17 poptart packages, 
#how likely is it that I will be able to buy some poptarts on Friday afternoon?
mean_poptarts = 3
std = 1.5 
days = 5

poptarts_eaten = np.round(np.random.normal(loc = 3, scale = 1.5, size = (10_000, days)))
poptarts_eaten

poptarts_per_week = poptarts_eaten.sum(axis=1)
(poptarts_per_week <= 17).mean()



0.7691

In [96]:
#review
#average # of poptarts consumed
pop_avg = 3
#deviation of poptarts:1.5
pop_std = 1.5
n_trials = 5
n_sims = 1_000_000
#simulated consumed poptarts
consumed = np.random.normal(pop_avg, pop_std, size = (n_sims, n_trials))
consumed


array([[2.30975202, 2.57853272, 2.93136502, 2.25543332, 3.44352865],
       [3.95122098, 4.65426658, 2.75664657, 2.7072859 , 3.24687066],
       [4.09012206, 4.3659959 , 3.46799981, 4.3849494 , 4.43543217],
       ...,
       [2.00226116, 4.4510013 , 1.88539449, 1.7708638 , 2.38866051],
       [1.15301449, 3.11665953, 1.48971391, 2.38252274, 3.92580112],
       [1.00387933, 4.01268037, 4.07353145, 2.58774648, 2.73680957]])

In [98]:
calculated = (consumed.sum(axis=1) >= 17).mean()
calculated

0.276138

In [22]:
#5. Compare Heights

# -Men have an average height of 178 cm and standard deviation of 8cm.
# -Women have a mean of 170, sd = 6cm.
# -If a man and woman are chosen at random, P(woman taller than man)?

men_height = 178
men_std = 8
women_height = 170
women_std = 6

men = np.random.normal(loc = men_height, scale = men_std, size = (10_000))
women =  np.random.normal(loc = women_height, scale = women_std, size = (10_000))

(women > men).mean()

0.2078

In [55]:
#6. When installing anaconda on a student's computer, 
# there's a 1 in 250 (.004) chance that the download is corrupted and the installation fails. 
# What are the odds that after having 50 students download anaconda, 
# no one has an installation issue? 100 students?
# What is the probability that we observe an installation issue within the first 150 students 
# that download anaconda?
# How likely is it that 450 students all download anaconda without an issue?
#50
outcome = [1,0] #1 = fails, 0=downloads
corrupt = np.random.choice(outcome, size=(10_000, 50), p=[1/250, 249/250])

corrupt_sum = corrupt.sum(axis=1) #axis=1 means sum acrosss all the rows
(corrupt_sum == 0 ).mean() #should be .816

# Binomial way (50):
# corrupt = sum(np.random.binomial(50, .004, 10_000))
# corrupt_sum = sum(np.random.binomial(50, .004, 100_000) 
# (corrupt_sum== 0).mean()

0.8177

In [102]:
#review
nsims = 1_000_000
ntrials = 50
failure = 1
success = 0

installs = np.random.choice([failure, success], size=(nsims, ntrials), p=[1/250,249/250])


In [103]:
calculate = (installs.sum(axis=1) > 0).mean()
calculate

0.181171

In [56]:
#100
outcome = [1,0] #1 = fails, 0=downloads
corrupt = np.random.choice(outcome, size=(10_000, 100), p=[1/250, 249/250])
corrupt_sum = corrupt.sum(axis=1) #axis=1 means sum acrosss all the rows
(corrupt_sum == 0 ).mean()

0.6729

In [72]:
# What is the probability that we observe an installation issue within the first 150 students 
# that download anaconda?
outcome = [1,0] #1 = fails, 0=downloads
corrupt = np.random.choice(outcome, size=(10_000, 150), p=[1/250, 249/250])
corrupt_sum = corrupt.sum(axis=1) #axis=1 means sum acrosss all the rows
(corrupt_sum > 0 ).mean()


0.4617

In [59]:
# How likely is it that 450 students all download anaconda without an issue?
outcome = [1,0] #1 = fails, 0=downloads
corrupt = np.random.choice(outcome, size=(10_000, 450), p=[1/250, 249/250])
corrupt_sum = corrupt.sum(axis=1) #axis=1 means sum acrosss all the rows
(corrupt_sum == 0 ).mean()



0.1687

In [109]:
#7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
# However, you haven't seen a food truck there in 3 days. How unlikely is this?
# How likely is it that a food truck will show up sometime this week?
prob = .70
outcomes = [1, 0] #1= not there, 0=there
food_truck = np.random.choice(outcomes, size=(1_000_000, 3), p=[.30,.70])
food_truck_sum = food_truck.sum(axis=1)
(food_truck_sum >= 3).mean()

0.026795

In [104]:
#review
nsims = 1_000_000
ntrials = 3
foodtruck = 1
notruck = 0
lunchdays = np.random.choice([foodtruck, notruck], size = (nsims,ntrials), p = [.7,.3])

In [106]:
calculated = (lunchdays.sum(axis=1) == 0).mean()
calculated

0.026889

In [110]:
nsims = 1_000_000
ntrials = 2
foodtruck = 1
notruck = 0
lunchdays = np.random.choice([foodtruck, notruck], size = (nsims,ntrials), p = [.7,.3])

In [111]:
calculated = (lunchdays.sum(axis=1) > 0).mean()
calculated

0.910331

In [74]:
#8. If 23 people are in the same room, what are the odds that two of them share a birthday? 
# What if it's 20 people? 40?
#theoretical = 
birthdays = list(range(1,366))
birthdays
df = pd.DataFrame(birthdays, columns = ['Day'])
df


Day
0      1
1      2
2      3
3      4
4      5
..   ...
360  361
361  362
362  363
363  364
364  365

[365 rows x 1 columns]

In [ ]:
#review

#days in a year

#23 people in the room

#we want an instance where both are the same number



In [120]:
#represent our datas possible outcomes, the number of days in a year
outcomes = list(range(0,365))
#create the data
nsims = 1_000_000
ntrials = 23

In [121]:
#lets get out sims, make a sim of 1 million classrooms of 23 students

classrooms = np.random.choice(outcomes, size=(nsims,ntrials))

In [122]:
classrooms

array([[  8, 134, 332, ...,   8, 314, 327],
       [283, 333, 259, ..., 245, 354, 171],
       [ 84, 264, 273, ..., 161, 260,  21],
       ...,
       [152,  23, 345, ..., 175, 174,  35],
       [274, 169, 345, ..., 186, 209,  40],
       [ 54,  10, 292, ..., 332,  43, 112]])

In [123]:
len(classrooms[0])

23